var fish = {
    "anchovy": {
        "hours": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20
        ], 
        "image": "", 
        "index": 1, 
        "location": "Sea", 
        "name": "Anchovy", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 200, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "angelfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 2, 
        "location": "River", 
        "name": "Angelfish", 
        "northern": [
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ], 
        "price": 3000, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            11, 
            12
        ]
    }, 
    "arapaima": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 3, 
        "location": "River", 
        "name": "Arapaima", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 10000, 
        "size": "6", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "arowana": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 4, 
        "location": "River", 
        "name": "Arowana", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 10000, 
        "size": "4", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "barred_knifejaw": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 5, 
        "location": "Sea", 
        "name": "Barred knifejaw", 
        "northern": [
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11
        ], 
        "price": 5000, 
        "size": "3", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "barreleye": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 6, 
        "location": "Sea", 
        "name": "Barreleye", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 15000, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "betta": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 7, 
        "location": "River", 
        "name": "Betta", 
        "northern": [
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ], 
        "price": 2500, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            11, 
            12
        ]
    }, 
    "bitterling": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 8, 
        "location": "River", 
        "name": "Bitterling", 
        "northern": [
            1, 
            2, 
            3, 
            11, 
            12
        ], 
        "price": 900, 
        "size": "1", 
        "southern": [
            5, 
            6, 
            7, 
            8, 
            9
        ]
    }, 
    "black_bass": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 9, 
        "location": "River", 
        "name": "Black bass", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 400, 
        "size": "4", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "blowfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 10, 
        "location": "Sea", 
        "name": "Blowfish", 
        "northern": [
            1, 
            2, 
            11, 
            12
        ], 
        "price": 5000, 
        "size": "3", 
        "southern": [
            5, 
            6, 
            7, 
            8
        ]
    }, 
    "blue_marlin": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 11, 
        "location": "Pier", 
        "name": "Blue marlin", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            7, 
            8, 
            9, 
            11, 
            12
        ], 
        "price": 10000, 
        "size": "6", 
        "southern": [
            1, 
            2, 
            3, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ]
    }, 
    "bluegill": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 12, 
        "location": "River", 
        "name": "Bluegill", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 180, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "butterfly_fish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 13, 
        "location": "Sea", 
        "name": "Butterfly fish", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9
        ], 
        "price": 1000, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            10, 
            11, 
            12
        ]
    }, 
    "carp": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 14, 
        "location": "Pond", 
        "name": "Carp", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 300, 
        "size": "4", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "catfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 15, 
        "location": "Pond", 
        "name": "Catfish", 
        "northern": [
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ], 
        "price": 800, 
        "size": "4", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            11, 
            12
        ]
    }, 
    "char": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 16, 
        "location": "River (Clifftop) Pond", 
        "name": "Char", 
        "northern": [
            3, 
            4, 
            5, 
            6, 
            9, 
            10, 
            11
        ], 
        "price": 3800, 
        "size": "3", 
        "southern": [
            3, 
            4, 
            5, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "cherry_salmon": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 17, 
        "location": "River (Clifftop) Pond", 
        "name": "Cherry salmon", 
        "northern": [
            3, 
            4, 
            5, 
            6, 
            9, 
            10, 
            11
        ], 
        "price": 1000, 
        "size": "3", 
        "southern": [
            3, 
            4, 
            5, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "clownfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 18, 
        "location": "Sea", 
        "name": "Clownfish", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9
        ], 
        "price": 650, 
        "size": "1", 
        "southern": [
            1, 
            2, 
            3, 
            10, 
            11, 
            12
        ]
    }, 
    "coelacanth": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 19, 
        "location": "Sea (Raining)", 
        "name": "Coelacanth", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 15000, 
        "size": "6", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "crawfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 20, 
        "location": "Pond", 
        "name": "Crawfish", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9
        ], 
        "price": 200, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            10, 
            11, 
            12
        ]
    }, 
    "crucian_carp": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 21, 
        "location": "River", 
        "name": "Crucian carp", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 160, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "dab": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 22, 
        "location": "Sea", 
        "name": "Dab", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            10, 
            11, 
            12
        ], 
        "price": 300, 
        "size": "3", 
        "southern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ]
    }, 
    "dace": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 23, 
        "location": "River", 
        "name": "Dace", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 240, 
        "size": "3", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "dorado": {
        "hours": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20
        ], 
        "image": "", 
        "index": 24, 
        "location": "River", 
        "name": "Dorado", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 15000, 
        "size": "5", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "football_fish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 25, 
        "location": "Sea", 
        "name": "Football fish", 
        "northern": [
            1, 
            2, 
            3, 
            11, 
            12
        ], 
        "price": 2500, 
        "size": "4", 
        "southern": [
            5, 
            6, 
            7, 
            8, 
            9
        ]
    }, 
    "freshwater_goby": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 26, 
        "location": "River", 
        "name": "Freshwater goby", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 400, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "frog": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 27, 
        "location": "Pond", 
        "name": "Frog", 
        "northern": [
            5, 
            6, 
            7, 
            8
        ], 
        "price": 120, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            11, 
            12
        ]
    }, 
    "gar": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 28, 
        "location": "Pond", 
        "name": "Gar", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 6000, 
        "size": "6", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "giant_snakehead": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 29, 
        "location": "Pond", 
        "name": "Giant snakehead", 
        "northern": [
            6, 
            7, 
            8
        ], 
        "price": 5500, 
        "size": "5", 
        "southern": [
            1, 
            2, 
            12
        ]
    }, 
    "giant_trevally": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 30, 
        "location": "Pier", 
        "name": "Giant trevally", 
        "northern": [
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ], 
        "price": 4500, 
        "size": "5", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            11, 
            12
        ]
    }, 
    "golden_trout": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 31, 
        "location": "River (Clifftop)", 
        "name": "Golden trout", 
        "northern": [
            3, 
            4, 
            5, 
            9, 
            10, 
            11
        ], 
        "price": 15000, 
        "size": "3", 
        "southern": [
            3, 
            4, 
            5, 
            9, 
            10, 
            11
        ]
    }, 
    "goldfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 32, 
        "location": "Pond", 
        "name": "Goldfish", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 1300, 
        "size": "1", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "great_white_shark": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 33, 
        "location": "Sea", 
        "name": "Great white shark", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 15000, 
        "size": "6 (Fin)", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "guppy": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 34, 
        "location": "River", 
        "name": "Guppy", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11
        ], 
        "price": 1300, 
        "size": "1", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            10, 
            11, 
            12
        ]
    }, 
    "hammerhead_shark": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 35, 
        "location": "Sea", 
        "name": "Hammerhead shark", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 8000, 
        "size": "6 (Fin)", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "horse_mackerel": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 36, 
        "location": "Sea", 
        "name": "Horse mackerel", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 150, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "killifish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 37, 
        "location": "Pond", 
        "name": "Killifish", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8
        ], 
        "price": 300, 
        "size": "1", 
        "southern": [
            1, 
            2, 
            10, 
            11, 
            12
        ]
    }, 
    "king_salmon": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 38, 
        "location": "River (Mouth)", 
        "name": "King salmon", 
        "northern": [
            9
        ], 
        "price": 1800, 
        "size": "6", 
        "southern": [
            3
        ]
    }, 
    "koi": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 39, 
        "location": "Pond", 
        "name": "Koi", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 4000, 
        "size": "4", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "loach": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 40, 
        "location": "River", 
        "name": "Loach", 
        "northern": [
            3, 
            4, 
            5
        ], 
        "price": 400, 
        "size": "2", 
        "southern": [
            9, 
            10, 
            11
        ]
    }, 
    "mahi-mahi": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 41, 
        "location": "Pier", 
        "name": "Mahi-mahi", 
        "northern": [
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ], 
        "price": 6000, 
        "size": "5", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            11, 
            12
        ]
    }, 
    "mitten_crab": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 42, 
        "location": "River", 
        "name": "Mitten crab", 
        "northern": [
            9, 
            10, 
            11
        ], 
        "price": 2000, 
        "size": "2", 
        "southern": [
            3, 
            4, 
            5
        ]
    }, 
    "moray_eel": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 43, 
        "location": "Sea", 
        "name": "Moray eel", 
        "northern": [
            8, 
            9, 
            10
        ], 
        "price": 2000, 
        "size": "Narrow", 
        "southern": [
            2, 
            3, 
            4
        ]
    }, 
    "napoleonfish": {
        "hours": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20
        ], 
        "image": "", 
        "index": 44, 
        "location": "Sea", 
        "name": "Napoleonfish", 
        "northern": [
            7, 
            8
        ], 
        "price": 10000, 
        "size": "6", 
        "southern": [
            1, 
            2
        ]
    }, 
    "neon_tetra": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 45, 
        "location": "River", 
        "name": "Neon tetra", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11
        ], 
        "price": 500, 
        "size": "1", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            10, 
            11, 
            12
        ]
    }, 
    "nibble_fish": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 46, 
        "location": "River", 
        "name": "Nibble fish", 
        "northern": [
            5, 
            6, 
            7, 
            8, 
            9
        ], 
        "price": 1500, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            11, 
            12
        ]
    }, 
    "oarfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 47, 
        "location": "Sea", 
        "name": "Oarfish", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            12
        ], 
        "price": 9000, 
        "size": "6", 
        "southern": [
            6, 
            7, 
            8, 
            9, 
            10, 
            11
        ]
    }, 
    "ocean_sunfish": {
        "hours": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20
        ], 
        "image": "", 
        "index": 48, 
        "location": "Sea", 
        "name": "Ocean sunfish", 
        "northern": [
            7, 
            8, 
            9
        ], 
        "price": 4000, 
        "size": "6 (Fin)", 
        "southern": [
            1, 
            2, 
            3
        ]
    }, 
    "olive_flounder": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 49, 
        "location": "Sea", 
        "name": "Olive flounder", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 800, 
        "size": "5", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "pale_chub": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 50, 
        "location": "River", 
        "name": "Pale chub", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 200, 
        "size": "1", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "pike": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 51, 
        "location": "River", 
        "name": "Pike", 
        "northern": [
            9, 
            10, 
            11, 
            12
        ], 
        "price": 1800, 
        "size": "5", 
        "southern": [
            3, 
            4, 
            5, 
            6
        ]
    }, 
    "piranha": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 52, 
        "location": "River", 
        "name": "Piranha", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 2500, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "pond_smelt": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 53, 
        "location": "River", 
        "name": "Pond smelt", 
        "northern": [
            1, 
            2, 
            12
        ], 
        "price": 500, 
        "size": "2", 
        "southern": [
            6, 
            7, 
            8
        ]
    }, 
    "pop-eyed_goldfish": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 54, 
        "location": "Pond", 
        "name": "Pop-eyed goldfish", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 1300, 
        "size": "1", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "puffer_fish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 55, 
        "location": "Sea", 
        "name": "Puffer fish", 
        "northern": [
            7, 
            8, 
            9
        ], 
        "price": 250, 
        "size": "3", 
        "southern": [
            1, 
            2, 
            3
        ]
    }, 
    "rainbowfish": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 56, 
        "location": "River", 
        "name": "Rainbowfish", 
        "northern": [
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ], 
        "price": 800, 
        "size": "1", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            11, 
            12
        ]
    }, 
    "ranchu_goldfish": {
        "hours": [
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15
        ], 
        "image": "", 
        "index": 57, 
        "location": "Pond", 
        "name": "Ranchu goldfish", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 4500, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "ray": {
        "hours": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20
        ], 
        "image": "", 
        "index": 58, 
        "location": "Sea", 
        "name": "Ray", 
        "northern": [
            8, 
            9, 
            10, 
            11
        ], 
        "price": 3000, 
        "size": "5", 
        "southern": [
            2, 
            3, 
            4, 
            5
        ]
    }, 
    "red_snapper": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 59, 
        "location": "Sea", 
        "name": "Red snapper", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 3000, 
        "size": "4", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "ribbon_eel": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 60, 
        "location": "Sea", 
        "name": "Ribbon eel", 
        "northern": [
            6, 
            7, 
            8, 
            9, 
            10
        ], 
        "price": 600, 
        "size": "Narrow", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            12
        ]
    }, 
    "saddled_bichir": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 61, 
        "location": "River", 
        "name": "Saddled bichir", 
        "northern": [
            1, 
            2, 
            3, 
            12
        ], 
        "price": 4000, 
        "size": "4", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "salmon": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 62, 
        "location": "River (Mouth)", 
        "name": "Salmon", 
        "northern": [
            9
        ], 
        "price": 700, 
        "size": "4", 
        "southern": [
            3
        ]
    }, 
    "saw_shark": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 63, 
        "location": "Sea", 
        "name": "Saw shark", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 12000, 
        "size": "6 (Fin)", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "sea_bass": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 64, 
        "location": "Sea", 
        "name": "Sea bass", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 400, 
        "size": "5", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "sea_butterfly": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 65, 
        "location": "Sea", 
        "name": "Sea butterfly", 
        "northern": [
            1, 
            2, 
            3, 
            12
        ], 
        "price": 1000, 
        "size": "1", 
        "southern": [
            6, 
            7, 
            8, 
            9
        ]
    }, 
    "seahorse": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 66, 
        "location": "Sea", 
        "name": "Seahorse", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11
        ], 
        "price": 1100, 
        "size": "1", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            10, 
            11, 
            12
        ]
    }, 
    "snapping_turtle": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 67, 
        "location": "River", 
        "name": "Snapping turtle", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ], 
        "price": 5000, 
        "size": "5", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            10, 
            11, 
            12
        ]
    }, 
    "soft-shelled_turtle": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 68, 
        "location": "River", 
        "name": "Soft-shelled turtle", 
        "northern": [
            8, 
            9
        ], 
        "price": 3750, 
        "size": "4", 
        "southern": [
            2, 
            3
        ]
    }, 
    "squid": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 69, 
        "location": "Sea", 
        "name": "Squid", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            12
        ], 
        "price": 500, 
        "size": "3", 
        "southern": [
            1, 
            2, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "stringfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 70, 
        "location": "River (Clifftop)", 
        "name": "Stringfish", 
        "northern": [
            1, 
            2, 
            3, 
            12
        ], 
        "price": 15000, 
        "size": "5", 
        "southern": [
            6, 
            7, 
            8, 
            9
        ]
    }, 
    "sturgeon": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 71, 
        "location": "River (Mouth)", 
        "name": "Sturgeon", 
        "northern": [
            1, 
            2, 
            3, 
            9, 
            10, 
            11, 
            12
        ], 
        "price": 10000, 
        "size": "6", 
        "southern": [
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9
        ]
    }, 
    "suckerfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 72, 
        "location": "Sea", 
        "name": "Suckerfish", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 1500, 
        "size": " 6 (Fin)", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "surgeonfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 73, 
        "location": "Sea", 
        "name": "Surgeonfish", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9
        ], 
        "price": 1000, 
        "size": "2", 
        "southern": [
            1, 
            2, 
            3, 
            10, 
            11, 
            12
        ]
    }, 
    "sweetfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 74, 
        "location": "River", 
        "name": "Sweetfish", 
        "northern": [
            7, 
            8, 
            9
        ], 
        "price": 900, 
        "size": "3", 
        "southern": [
            1, 
            2, 
            3
        ]
    }, 
    "tadpole": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 75, 
        "location": "Pond", 
        "name": "Tadpole", 
        "northern": [
            3, 
            4, 
            5, 
            6, 
            7
        ], 
        "price": 100, 
        "size": "1", 
        "southern": [
            1, 
            9, 
            10, 
            11, 
            12
        ]
    }, 
    "tilapia": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 76, 
        "location": "River", 
        "name": "Tilapia", 
        "northern": [
            6, 
            7, 
            8, 
            9, 
            10
        ], 
        "price": 800, 
        "size": "3", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            12
        ]
    }, 
    "tuna": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 77, 
        "location": "Pier", 
        "name": "Tuna", 
        "northern": [
            1, 
            2, 
            3, 
            4, 
            11, 
            12
        ], 
        "price": 7000, 
        "size": "6", 
        "southern": [
            5, 
            6, 
            7, 
            8, 
            9, 
            10
        ]
    }, 
    "whale_shark": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 78, 
        "location": "Sea", 
        "name": "Whale shark", 
        "northern": [
            6, 
            7, 
            8, 
            9
        ], 
        "price": 13000, 
        "size": "6 (Fin)", 
        "southern": [
            1, 
            2, 
            3, 
            12
        ]
    }, 
    "yellow_perch": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 79, 
        "location": "River", 
        "name": "Yellow perch", 
        "northern": [
            1, 
            2, 
            3, 
            10, 
            11, 
            12
        ], 
        "price": 300, 
        "size": "3", 
        "southern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9
        ]
    }, 
    "zebra_turkeyfish": {
        "hours": [
            0, 
            1, 
            2, 
            3, 
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11, 
            12, 
            13, 
            14, 
            15, 
            16, 
            17, 
            18, 
            19, 
            20, 
            21, 
            22, 
            23
        ], 
        "image": "", 
        "index": 80, 
        "location": "Sea", 
        "name": "Zebra turkeyfish", 
        "northern": [
            4, 
            5, 
            6, 
            7, 
            8, 
            9, 
            10, 
            11
        ], 
        "price": 500, 
        "size": "3", 
        "southern": [
            1, 
            2, 
            3, 
            4, 
            5, 
            10, 
            11, 
            12
        ]
    }
}